### ISSUE TITLE
Overlapping accesses to 'phraseData', but modification requires exclusive access; consider copying to a local variable

### ISSUE THREAD

**Issue by MRYIN123** [hodlwallet/hodl-wallet-ios#59]
guard phraseData.withUnsafeMutableBytes({
                BRBIP39Encode($0, phraseData.count, &words, entropyRef, MemoryLayout<UInt128>.size)
            }) == phraseData.count else { return nil }

show error like this: Overlapping accesses to 'phraseData', but modification requires exclusive access; consider copying to a local variable

swift 4, xcode 10, ios12
how can i fix it?

**Comment by igorgue** [comment]
@MRYIN123 Hey, we're working on it, unfortunately right now the only way to build the project is with XCode 9.
