### ISSUE TITLE
App Crashing

### ISSUE THREAD

**Issue by TSpeedman** [hodlwallet/hodl-wallet-ios#65]
App crashing when checking tx info:

![451F268B-BEBA-4767-A2DE-2243028DAA6C](https://user-images.githubusercontent.com/49999385/57562442-96b7a200-7347-11e9-945e-c962c9d28a55.gif)

**Comment by igorgue** [comment]
Hi @TSpeedman do you happen to know what's the address? I might be able to debug it if I have the transaction.

It's unfortunate though, for any case please make sure you have your seed backed up. Let me know and I'll see how to debug it.

**Comment by TSpeedman** [comment]
Here is the address:
bc1q0hg84p7k5mjqllsussly59cm2p5mme9lj6a8z0  

I have the seed, have wiped the wallet from the app and am now  restoring (someone suggested I do this). I haven’t had time to let the blockchain sync, but once that’s happened, I’ll see if the app still crashes.

**Comment by igorgue** [comment]
@TSpeedman depending on your network and the bitcoin network itself, it might take a while (up to 3hours) and your phone needs to up. I recommend connecting it. Hodl will resume from where you left it. Just give it time to finish.

I was able to find the transaction I'll do some tests here https://blockstream.info/tx/182444d6eaa886ea148dcdb498025c8492f2479fc2c99422b811bb6bbf498efc

**Comment by TSpeedman** [comment]
@igorgue thanks. Will report back once synced.

**Comment by TSpeedman** [comment]
@igorgue Fixed! 
1) Removed/wiped wallet
2) Re-add wallet with seed words
3) Sync blockchain
4) Success

Thanks for your help.

**Comment by TSpeedman** [comment]
@igorgue Don't know how to re-open the issue but it's crashing again :( I just send a new tx (same address as previous) and when I click the transaction it is crashing.

I've removed the wallet, re-added, and fully synced the blockchain. It's doing the same thing as in the GIF above.

**Comment by igorgue** [comment]
Hi @TSpeedman I just pushed some fixes for the transaction parser, the release should be up in the next few days and would fix errors like yours (and I had that error as well).
