### ISSUE TITLE
[Suggestion] Show unconfirmed transactions greyed out.

### ISSUE THREAD

**Issue by 1n5aN1aC** [hodlwallet/hodl-wallet-ios#70]
I understand that unconfirmed transactions should not be trusted, but it would be much appreciated to have those unconfirmed transactions appear in the app, but just be greyed out significantly, making it obvious these are not real yet.

As it is, it can be difficult to even be confident a transaction has been accepted without using something outside of the app.

**Comment by 1n5aN1aC** [comment]
Update:  Works as expected for normal addresses, but this appears to be the case for incoming transactions to a legacy address.

**Comment by igorgue** [comment]
@1n5aN1aC hey thanks for the report. I honestly have never seen the grayed-out background on the tx, is it on the list?

Do you mean the text that says `Awaiting Confirmation`?

**Comment by igorgue** [comment]
@1n5aN1aC about unconfirmed transactions, many people like to accept unconfirmed transactions even at some businesses, it's really hard to pull out an attack to fake them, generally speaking, we do allow spending of unconfirmed transactions, it'll just wait until that transaction is confirmed to send the other one.

**Comment by 1n5aN1aC** [comment]
Sorry, the ticket was named before I did more testing.

Originally, I thought unconfirmed transactions weren't showing AT ALL, which they are now doing so.  So I was originally suggesting that you make unconfirmed transactions display, but just greyed out, as obviously they should be visually different.  I now know you make `Awaiting Confirmation` display, which works well.

After more testing, I'm not sure what was wrong, but it's all working now.  All transactions are now appearing pretty reliably, whether unconfirmed or confirmed.

Perhaps it was just a bug or a node that had fallen behind, but the first transaction to the wallet did not show up until it was confirmed.  (It was to a legacy address)  So the problem is now 'fixed' for me.  Only the first incoming transaction did not appear for over an hour, even killing and restarting the app, resyncing, etc.

**Comment by igorgue** [comment]
@1n5aN1aC Yeah sometimes it happens, I'd say if you restart the app it'll give you new nodes! We've noticed some seeds get stuck in the process some others don't, only a well-connected node would notify you of a tx instantly. We also have the feature to connect to your own node if you want a, probably, better experience or at least something you can control. But really just restarting the app will give you a new node.

To check your node IP address you can go to `Menu -> Settings -> Advanced -> Bitcoin Nodes`.
